### ISSUE TITLE
[Feature] 택시팟 생성 시간 선택 UI 업데이트

### ISSUE THREAD

**Issue by jsyworks** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#174]
## Description
UT 중 택시팟 생성 시간 선택에서 오전/오후 구분을 잘 수행하지 못하는 유저 피드백 발견
해당 UI A,B안 업데이트

## Sketch Screenshot
<img src= "https://user-images.githubusercontent.com/52963399/176357743-ea857433-7106-49f3-851b-8e2aa4d55f6a.svg" width= "300"> <img src= "https://user-images.githubusercontent.com/52963399/176357745-534af8f3-6b40-42af-aab5-90c3b656c667.svg" width= "300">

## To-do
- [x] A, B 안중에 팀 회의 후 픽스

**Comment by HoJongPARK** [comment]
저는 A 안이 더 좋아보이네요~~
