### ISSUE TITLE
[Feature] 로그인 화면 UI 제작

### ISSUE THREAD

**Issue by jsyworks** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#176]
## Description
로그인 화면 UI를 제작
기존의 로그인 환영 화면을 토스트 메시지 UI로 수정했습니다.

## Sketch Screenshot
<img width="576" alt="image" src="https://user-images.githubusercontent.com/52963399/176370559-6d95f836-4928-43d5-baf9-e34dbc8a30ba.png">

**Comment by HoJongPARK** [comment]
지금 드는 생각인데, 비밀번호 없는 로그인으로 갈거면, 항상 로그인 과정이 똑같습니다
1. 이메일을 보낸다
2. 사용자는 해당 이메일에서 링크를 클릭해 우리 앱을 다시 실행한다.
3. 이메일 링크에 의해 앱이 다시 실행되면, 회원가입을 진행한다. 이미 존재하는 유저일 경우 바로 로그인을 시도한다.

따라서 로그인과 회원가입 화면이 분리될 필요는 없을 것 같습니다

@jsyworks
