### ISSUE TITLE
[Refactor] date formatter class 내부 코드 의존성 제거 (소통 오류)

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#211]
## Description
현재 코드 내부에서 date를 조작할 때 dateFormatter를 이용하고, 해당 formatter를 이용하여 string이나 int로 바꿔준 date+extension의 함수와 연산 프로퍼티를 직접 가져와 사용하고 있습니다.
이는 코드 의존성을 높여 변경이 필요할 때 직접 코드를 건드려야하는 불편함, 문제를 유발합니다.
이러한 의존성을 줄이기 위해 리팩토링을 진행하려 합니다.

```swift
//Date+Extension.swift
extension Date {
private static let formatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy년 MMM"
        formatter.locale = Locale(identifier: "ko_KR")
        formatter.timeZone = TimeZone(abbreviation: "KST")
        return formatter
    }()

    private static let monthDayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "MM월 dd일"
        formatter.locale = Locale(identifier: "ko_KR")
        formatter.timeZone = TimeZone(abbreviation: "KST")
        return formatter
    }()

    private static let intFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyyMMdd"
        formatter.locale = Locale(identifier: "ko_KR")
        formatter.timeZone = TimeZone(abbreviation: "KST")
        return formatter
    }()
}
```
이런식으로 있는 DateFormatter를 아래의 class property에서 선언할 수 있도록 하려하는데 올바른 방법일까요?
```swift
struct CalendarView: View {
    private let dateFormatter: DateFormatter = Date.monthDayFormatter
// 해당 formatter를 바꿀 일이 있는 경우 아래와 같이 초기화 해주는 값만 바꿔주면 된다
    private let dateFormatter: DateFormatter = Date.intFormatter
}
```

기존에는 아래와 같이 Date를 String으로 바꿔줬다면
```swift
Text("\(currentDate.formattedString)")
```
이제는 관련 property를 선언했기 때문에 예를들어 아래와 같이 사용할 수 있게 되는것입니다
```swift
Text("\(dateFormatter.string(from: currentDate))")
```

**Comment by HoJongPARK** [comment]
이렇게 리팩토링 할 경우엔 기존의 방식이 더 좋습니다. 왜냐하면 기존엔 Date 에서 바로 읽을 수 있는 형태로 바꿀 수 있는데, 이럴 경우 사람이 읽을 수 있는 문자열로 뽑아내는 과정에서 dateFormatter 가 드러나지 않습니다. 따라서 내부 구현이 드러나지 않게 캡슐화가 잘 된거죠. 
물론 formattedString 이라는 프로퍼티 이름이 얼마나 의미있는 이름인지는 잘 모르겠습니다. 

다른 개발자가 Date 의 formattedString 이라는 프로퍼티를 본다면... 이게 무슨 문자열을 반환할지 잘 모를 수도 있다 이거죠.

만약 2022년 7월 13일 의 형태로 반환하는 프로퍼티라면, readableYearMonthDate 라는 프로퍼티 이름이 더 적절할 수 있겠죠. 

어쩄든 기존의 방식은 dateFormatter 라는 세부 구현이 드러나지 않고, 사용하는 쪽에서 dateFormatter 의 존재를 모르기 때문에, dateFormatter 가 바뀌어도 formattedString 프로퍼티를 사용하는 쪽에서는 아무런 코드 변경이 필요없다 이겁니다. 

제가 말한 리팩토링은 이게 아니고, 

```swift
self.meetingMonth = taxiParty.meetingDate / 100 % 100
self.meetingDay = taxiParty.meetingDate % 100
self.meetingHour = String(format: "%02d", taxiParty.meetingTime / 100 % 100)
self.meetingMinute = String(format: "%02d", taxiParty.meetingTime % 100)
```
위와 같은 코드를 보면 TaxiParty 의 meetingTime 과 meetingDate 를 사람이 읽을 수 있는 형태로 만들기 위해서, 모듈러나 나누기 연산을 수행하는 것을 볼 수 있습니다. 즉 개발자가 TaxiParty 의 meetingDate 가 어떤 형태의 Int 인지 알아야하고, 이것을 사람이 읽을 수 있는 형태로 변환하기 위해 %100 과 같은 연산을 수행해야 한다는 사실을 알아야 한다는 것이죠.  

하지만 만약 여기서 TaxiParty 의 meetingDate 의 포맷이 바뀌어야 한다면 어떻게 될까요. meetingDate / 100 % 100 과 같은 연산을 수행하는 모든 코드들을 전부 수정해야 합니다. format 이 바뀌었기 때문에 구현 방식도 바뀌어야 하기 때문이죠. 즉 meetingDate 와 meetingTime 이라는 프로퍼티는 전부 내부 구현에 속하고, 이것을 충분히 감추지 못했고 적절한 프로퍼티를 제공해주지 못했기 때문에 위와 같은 참사가 일어난 것이죠.

위의 연산은 모두 Int 형태로 저장되있는 meetingTime 과 meetingDate 를 "2022년 7월 13일" 과 같이 사람이 직접 읽을 수 있는 문자열로 사용하기 위해 벌어진 일입니다.

따라서 TaxiParty 의 프로퍼티로 바로 저런 문자열을 읽어올 수 있도록 리팩토링 할 것을 추천드립니다.

```swift
struct TaxiParty {
  var readableDate: String {
    let dateFormatter: DateFormatter = DateFormatter....
    // taxiParty 내부의 meetingDate 를 문자열로 반환하기 위한 내부구현
   return readableString
  }
}
```

그러면 위와 같은 % 100 /100 과같은 코드가 taxiParty.readableDate 와 같이 프로퍼티로 추상화 될 수 있는 것입니다.

해당 프로퍼티를 사용하는 개발자가 복잡한 내부 구현까진 몰라도 된다 이거죠

**Comment by Chaeho-Min** [comment]
DateFormatter를 다루기 전 한가지 말씀드리자면, DateFormatter는 아주 비싼 아이입니다.
그래서 CalendarView나 TaxiParty 구조체에서 DateFormatter를 생성하게 되면, CalendarView나 TaxiParty가 초기화 될 때마다 DateFormatter가 생성되어 앱이 느려지지는 않을까 하는 우려가 드네요...

따라서 DateFormatter는 기존의 방식대로 extension에 두거나(그런데 Date 익스텐션에 DateFormatter가 있는 것에는 의문이 드네요) 싱글톤을 하나 만들어서 그 안에 DateFormatter를 두고, TaxiParty의 readableDate 변수에서는 이미 만들어져있는 DateFormatter를 불러와서 사용하는 방식이 더 좋다고 생각합니다!

- [DateFormatter가 얼마나 비싼지](https://sarunw.com/posts/how-expensive-is-dateformatter/)
- [메모리를 많이 써서 DateFormatter 속도를 향상시키는 방법](https://sarunw.com/posts/how-to-use-dateformatter/)
