### ISSUE TITLE
[Feature] 자동 로그인이 되는 동안 스플래시 이미지 표시

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#232]
## Description
현재는 자동 로그인이 되는 동안 `OnboardingView`가 띄워지도록 되어 있습니다.
이를 개선하여 로그인이 안 되어 있을 때는 로그인 화면이, 로그인이 되어 있을 때는 로그인이 진행되는 동안 회원가입 화면이 뜨도록 합니다.

## To-do
- [x] UserDefaults에 email, password가 저장되어 있으면 스플래시 이미지 표시, 저장되어 있지 않다면 `OnboardingView`표시

**Comment by HoJongPARK** [comment]
TaxiPartyState 라는 enumeration 을 참고하시기 바랍니다.

TaxiPartyList 의 택시파티 배열은 비동기적인 처리를 통해 불러와야 하는 데이터로, TaxiPartyState 는 이런 택시 파티 배열의 상태를 enum 의 각 case 로 나타내고 있습니다.

https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/blob/83e97246f7fae6f71a63424accd7a50de74ca83f/Taxi/Taxi/Presenter/TaxiPartyList/TaxiPartyState.swift#L9-L14

notRequested case 는 아직 load request 를 보내지 않은 초기 상태, 
isLoading 상태는 load request 를 보내서 데이터가 로딩 중인 상태, 
loaded 는 데이터가 성공적으로 로드되어서 데이터가 실제로 있는 상태,
empty 는 데이터가 성공적으로 로드되었지만 아무 택시팟도 존재하지 않는 상태, 
그리고 마지막으로 error 는 데이터를 불러올 때 에러가 뜬 상태를 나타냅니다.

즉 데이터의 상태를 위와같이 enum 으로 나타내는 것이 가능하고, 데이터와 상태를 enum 으로 같이 나타내면, 상태와 데이터가 동기화되지 않는 상황을 방지할 수 있습니다.

예를들어 원래대로 로딩 중인 상태는 @Published var isLoading: Bool 으로, 에러가 뜬 상태를 @Published var error :Error? 
와 같은 식으로 관리하면, 데이터를 나타내는 @Published var taxiParties: [TaxiParty] 프로퍼티와 error, isLoading 상태가 동기화되어야 합니다. taxiParties 가 성공적으로 불러와졌는데 개발자가 실수로 isLoading 이란 값을 false 로 바꿔주지 않으면, 데이터가 로드되었음에도 프로그레스 뷰를 계속 봐야하는 상황이 일어날 수도 있다는 겁니다.

enum 으로 데이터와 상태를 결합시키면 이런 상태 비동기화 현상을 방지할 수 있고, 어떤 상태를 가지고 있는지 명확하게 알 수 있으므로 UI 도 그리기 쉬워집니다.

https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/blob/83e97246f7fae6f71a63424accd7a50de74ca83f/Taxi/Taxi/Presenter/TaxiPartyList/TaxiPartyList.swift#L68-L82

위 코드는 taxiPartyState 에 따라 알맞은 UI 를 띄워주는 코드입니다

위와 같이 마찬가지로 @AppState 의 UserInfo 를 enum 으로 관리할 수도 있다고 봅니다. 

```swift
enum UserInfoState {
case empty // 로그인 되지 않은 상태
case autoLogin // 자동 로그인 중인 상태
// 기타 필요한 상태들... 
}

final class AppState: ObservableObject {
  @Published private (set) var userInfo: UserInfo = .empty
}
```

와 같이 리팩토링해서 원하고자 하는 바를 쉽게 얻을 수 있을 것 같습니다. 기존에 위와 같은 방식으로 참고된 코드들을 참고해서 리팩토링을 진행해보세요.
