### ISSUE TITLE
[BUG] 채팅창 나가기 버그

### ISSUE THREAD

**Issue by YoonyoungL** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#234]
## 버그내용
채팅창에 들어가 있는 상태에서 나가기를 누르면 에러가 납니다.
Fatal error: No ObservableObject of type ViewModel found. A View.environmentObject(_:) for ViewModel may be missing as an ancestor of this view. (lldb)

## 버그 재현
채팅창에 들어가 있는 상태에서 나가기를 누릅니다.

## Etc
ChatRoom에 뷰모델을 전달 안해줘서 생기는 오류 같습니다.
MyPartyView의 120줄의 
```swift
ChatRoomView(party: party, user: authentication.userInfo)
```
```swift
ChatRoomView(party: party, user: authentication.userInfo)
    .environmentObject(self.viewModel)
```
위 코드를 아래로 바꿔주면 해결 가능할 것 같습니다.

**Comment by HoJongE** [comment]
아하 제가 리팩토링을 진행하면서 ViewModel 을 environmentObject 로 넘기지 않고 의존성 주입을 사용해 넘기는 방법으로 수정했는데, 이것 때문에 기존 environmentObject 를 사용하던 코드가 작동하지 않던 것이었네요!
