### ISSUE TITLE
[Feature] SwiftLint 적용

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#4]
## Description
Xcode SwiftLint 적용

## To-do
- [x] (개인 별) mac os swiftLint 설치
- [x] (호종이 작업) xcode swiftLint run script 추가
- [x] 요셉
- [x] 아보
- [x] 조이
- [x] 제리
- [x] 레이몬드
### Mac os에 SwiftLint 설치하는 법

1. Mac os 에 home brew 패키지 매니저 설치하기 [Home brew 설치 가이드 사이트](https://eunhee-programming.tistory.com/259)
2. 터미널에 다음 명령어 입력 
```swift
brew install swiftlint
```
3. 각자 mac 에 homebrew 로 swiftLint 설치 후 task 완료 바랍니다.

**Comment by HoJongPARK** [comment]
> brew install SwiftLint만 했는데 이거면 되나요?

네

**Comment by luminouxx** [comment]
멋있네요 역시 호종이 화이팅

**Comment by Gobans** [comment]
멋있어요
