### ISSUE TITLE
[Help] 유저 정보 관리

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#45]
매 뷰마다 파이어베이스에서 유저 정보를 불러와서 url을 통해 이미지를 다운받는 것은 뭔가 안 좋을 것 같습니다.
유저 정보를 어떻게 관리해야될지 도움을 요청합니다!
- 어플 실행시 유저 정보를 불러와서 닉네임과 프사를 (어플이 켜져있는 동안만) 저장해두고, 다른 뷰에서 갖다 쓰는지,
- 아니면 닉네임과 프사는 어차피 프로필 관리 화면에서만 바꿀 수 있으니까 기기에 저장해두고 프로필 관리 화면에서 변경시 기기에 저장된 것을 업데이트함과 동시에 파이어베이스에도 업로드 해야 하는지,
- 아니면 파이어베이스가 알아서 캐시까지 다 해주는지(캐시로 해줘도 이미지가 url이라 의미 없을것이라 예상).

백엔드?에서 데이터를 가져와서 쓰는건 처음이라 너무 어렵네요ㅠㅠ 도와주세요!

**Comment by SH0123** [comment]
저도 궁금합니다... 레퍼런스 찾아보려하는데 잘 못찾겠네요 
@HoJongPARK

**Comment by HoJongPARK** [comment]
1. Image를 캐시처리해서 네트워크 비용을 최소화할 수도 있고, SDWebImageSwiftUI 라이브러리를 사용한다면 url 로 이미지 다운로드 알아서 캐시처리를 해줍니다.
2. Firebase 에서도 캐시 처리를 해주긴 하지만, 이미지는 SDWebImageSwiftUI 를 사용하면 url 만 넣어도 자동으로 불러와주고 캐시처리까지 알아서 다 해줍니다.

**Comment by Chaeho-Min** [comment]
> * Image를 캐시처리해서 네트워크 비용을 최소화할 수도 있고, SDWebImageSwiftUI 라이브러리를 사용한다면 url 로 이미지 다운로드 알아서 캐시처리를 해줍니다.
> * Firebase 에서도 캐시 처리를 해주긴 하지만, 이미지는 SDWebImageSwiftUI 를 사용하면 url 만 넣어도 자동으로 불러와주고 캐시처리까지 알아서 다 해줍니다.

일단 SDWebImageSwiftUI로 구현해보겠습니다 감사합니다~
