### ISSUE TITLE
[Help] AuthenticateUseCase 사용시 'Result of call to ... is unused' 경고가 뜨는 문제

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#55]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/75792767/173219589-28ccd9e0-7d5d-4d40-a5b8-f291411eb617.png">
AuthenticateUseCase를 사용하면 위와 같은 경고가 뜨게 됩니다.
찾아보니까 리턴값이 있는데 그 값을 받아주지 않고 호출하면 뜨는 경고인 것 같습니다.

제가 노란딱지가 있으면 잠을 못자는 성격이라, 이걸 해결하고 싶어서 보니까 @discardableResult를 사용하면 된다는데 얘를 써도 될까요?

```swift
@discardableResult
func changeNickname(_ user: User, to nickname: String) -> AnyPublisher<User, Error> {
    return userRepository.updateNickname(user, nickname)
}
```

## 참고
- http://seorenn.blogspot.com/2018/05/swift-result-of-call-is-unused.html

**Comment by HoJongPARK** [comment]
Combine Publisher 사용 방법에 대해 참고하시기 바랍니다.
- https://minosaekki.tistory.com/45
- [또한 테스트 파일에서 AnyPublisher 를 어떻게 사용하는지 참고하시기 바랍니다.](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/blob/main/Taxi/TaxiTests/UserRepositoryTest.swift)

만약 Combine 이 너무 어렵다면, completion 콜백 형태로도 사용할 수 있도록 API 를 추가하겠습니다.

**Comment by HoJongPARK** [comment]
completion 콜백 형태 API 추가 완료
