### ISSUE TITLE
[Please Read] 코드 작성, 커밋 시 항상 고려할 것 중 하나

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#77]
# 접근 제어

접근지정자란 public, private 과 같은 키워드로, 클래스, 구조체, 프로퍼티 등의 [은닉화](https://seungchan.tistory.com/entry/Swift-private-접근제어-캡슐화-은닉화) 를 위해 사용됩니다. 

우리가 항상 SwitUI View 구조체를 만들 때, @State 프로퍼티에 private 접근 지정자를 작성하라는 이유는, 해당 State 값이 작성된 View 내부에서만 사용가능하기 때문입니다. 즉 외부에서 접근조차 하지 못하게 만들어서 개발자의 실수로 생길 수 있는 오류를 미연에 방지하기 위함이기도 합니다. 

또한 [블로그 글](https://cocoacasts.com/improve-swift-performance-through-access-control) 에 따르면, 접근 제어는 다음과 같은 장점들을 가집니다

- **접근 지정자**의 작성은 그 자체로 communication 의 의미를 가진다. 개발자가 private 으로 지정한 인스턴스 메소드나 프로퍼티는, 절대 override 할 수 없고 내부 로직만을 위한 프로퍼티임을 의미한다. 다른 개발자들은 암시적으로 메소드나 프로퍼티의 사용 범위를 알 수 있다. 신중하게 선택된 하나의 단어가 코드를 문서화 시키는 것이다.
- **상수와 변수 (let, var)** 또한 그 자체로 communication 의미를 가진다고 생각합니다. 작성하는 개발자는 아무 생각 없이 var 와 let 을 혼용해서 쓸 수 있지만, 그것을 리뷰하는 다른 개발자들은 해당 프로퍼티가 변경의 여지가 있는지 없는지 나머지 코드를 보면서 스스로 판단해야 합니다. 
-  swift performance 가 향상된다. Method dispatch 라는 흥미로운 주제에 관해 이야기하는데, **관심 있으시면 읽어보세요**

다음과 같은 클래스가 있다고 가정해봅시다. 

```swift
class TestClass {
  func getComputedValue(value: Int) -> Int {
    let processedValue: Int = valueProcessing(value)
    return computeValue(processedValue)
  }

  func valueProcessing(value: Int) -> Int {
   //..,
  }
  
  func computeValue(value: Int) -> Int {
    //...
  }
}
```

- 위 클래스는 Int 데이터를 받아서 특정한 전처리를 한다음, 전처리한 데이터에 특정 연산을 거치고 유저에게 최종적으로 값을 반환합니다. 
- 해당 클래스를작성한 개발자의 의도는 유저가 **getComputedValue** 만 호출해서 원하는 동작을 수행하는 것입니다. 
- 그러나 다른 개발자들은**valueProcessing**, **computeValue** 메소드에도 접근할 수 있는데, 이 자체로 혼란을 줄 수 있습니다. 
-  해당 메소드들은 어떤 용도에 사용하는지 직접 생각해야하고, 최악의 경우 한 명 한 명 직접 찾아와서 물어볼 수도 있겠죠.
-  하지만 처음 작성할 때부터 private 메소드로 작성했다면, 이런 상황은 미연에 방지할 수 있습니다. 

**접근 제어의 역할은 이렇게 중요하고, 다음과 같이 View 내부적인 연산을 위해 필요한 프로퍼티들도 되도록이면 접근제어를 세심히 고려해주시기 바랍니다.**

```swift
struct TestView: View {
  private let day: [String] = ["월", "화", "수", ....]
  var body: some View {
    //...
  }
}
```

# 커밋할 때 불필요한 파일은 제외하기

이번 프로젝트를 하면서 가장 많이 나온 상황은, 직접 만든 View 를 테스트하기 위해 최상위 View에 직접 만든 뷰를 작성한 것입니다. 또한 여러가지 이유로 다른 파일들을 수정할 수 있습니다. 다른 클래스나 구조체 등을 테스트하기 위해 직접 코드를 수정해볼 수 있습니다. 그러나 단순 테스트를 위해 다른 파일을 수정했으면, 다음 커밋에서 해당 변경사항들은 모두 제외해야합니다. 후에 충돌의 원인이 될 수도 있고, 리뷰하는 사람도 의아합니다. 

**커밋 전 항상 변경사항을 찬찬히 살펴보는 시간을 가지고 원할한 협업을 하도록 합시다.** 

@pis3120 @SH0123 @Chaeho-Min @YoonyoungL @jsyworks

**Comment by YoonyoungL** [comment]
이번 프로젝트에서 많이 배워가는 것 같습니다. 앞으로 코드를 쓸 때 항상 생각해야겠네요!

**Comment by Chaeho-Min** [comment]
혼자 코딩할 때는 private이 코드에 전혀 지장을 주지 않았기 때문에 신경을 끄고 살았었는데, 협업에서는 이렇게나 중요한 아이였군요!
앞으로 private을 항상 고민하고 코드를 작성하겠습니다!

**Comment by SH0123** [comment]
좋은 글 감사합니다 ~ 유념하여 코드 작성하고 커밋 하겠습니다
