### ISSUE TITLE
[Help] 프로필 사진을 삭제하는 유즈케이스

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#78]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/75792767/173503489-cf490350-6ae7-45e1-bbc1-6571c63ea877.png">

프로필 사진을 삭제하려고 changeProfileImage에 nil을 넣었는데, 오류가 뜹니다.
유즈케이스를 보니까 User.profileImage를 다시 nil로 만드는 방법이 없는것 같습니다.

프로필 관리 화면에서 프로필 사진을 삭제하는 기능을 구현해야 할 것 같은데, 이러려면 새로운 유즈케이스가 필요할 것 같습니다!
혹은 현재 상태로 다른 방법이 있다면 알려주시면 감사하겠습니다.

**Comment by HoJongPARK** [comment]
아 새로운 유즈케이스를 추가하겠습니다. 참고로, Usecase 클래스를 View 에서 바로 불러오지 말고, ObservableObject 를 활용해서 ObservedObject 에서 유즈케이스를 호출하고 데이터를 변경하는 식으로 구현하는게 좋을 것 같습니다.

**Comment by HoJongPARK** [comment]
더 말씀드리자면, 유저 정보는 애플리케이션 전체 라이프사이클에서 지속되어야할 데이터이기 때문에, 원래 계획은 @EnvironmentObject 로 생성해서 유저 정보를 관리하고자 했습니다.

**Comment by HoJongPARK** [comment]
https://www.youtube.com/watch?v=vPCEIPL0U_k

여기 나오는대로 유저 정보를 관장하는 Authentication class 를 EnvironmentObject 로, 유저 정보를 변경하는 유즈케이스들은 해당 클래스에서 호출하고자 하는 방향이 맞는 것 같습니다

**Comment by Chaeho-Min** [comment]
> https://www.youtube.com/watch?v=vPCEIPL0U_k
> 
> 여기 나오는대로 유저 정보를 관장하는 Authentication class 를 EnvironmentObject 로, 유저 정보를 변경하는 유즈케이스들은 해당 클래스에서 호출하고자 하는 방향이 맞는 것 같습니다

한 번 보고 시도해 본 다음에 어려우면 도움 요청하겠습니다! 항상 감사합니다 Ho종

**Comment by HoJongPARK** [comment]
> > https://www.youtube.com/watch?v=vPCEIPL0U_k
> > 여기 나오는대로 유저 정보를 관장하는 Authentication class 를 EnvironmentObject 로, 유저 정보를 변경하는 유즈케이스들은 해당 클래스에서 호출하고자 하는 방향이 맞는 것 같습니다
> 
> 한 번 보고 시도해 본 다음에 어려우면 도움 요청하겠습니다! 항상 감사합니다 Ho종

ㄴㄴ
