### ISSUE TITLE
[Feature] 유저 정보를 관리하는 ObservableObject

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#81]
## 선행 작업
- [x] #38 
- [x] #69 

## Description
- 앱의 전체 사이클에서 지속될 유저 데이터 관리
- 닉네임 변경, 프로필 사진 변경 등의 유즈케이스

## 질문
- 파일 이름과 파일 위치가 어떻게 되어야 할지
- 제가 할 수 있을까요? ㅠㅠ

## To-do
- [x] 각 유즈케이스 호출 메서드 작성
- [x] User가 옵셔널일 때

## Etc
- 전 못할 것 같아요

**Comment by HoJongPARK** [comment]
못할 것 같다니... 자신감이 없군요

**Comment by Chaeho-Min** [comment]
무료 맛보기...! 감사합니다
