### ISSUE TITLE
[Please Read] Rebase 이후 유념하기

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#91]
PR을 보낼 때 develop과의 상태를 맞추기 위해 Rebase를 해왔습니다.
보통 Rebase 이후 force push를 하여 충돌 문제를 해결하였는데, 생각 없이 force push를 하다가 프로젝트 파일에 문제가 생겼습니다.
그러니 모두들 **Rebase 이후 force push 하기 전**에 **파일을 한 번 실행해봅시다** 꼭!!!

1. Rebase
2. conflict 해결
3. 파일 실행해보기
4. force push

**Comment by Chaeho-Min** [comment]
포스 푸시 전에 파일 체크 꼭 하기 확인이요~
